import type { Task } from './types';

export const mockTasks: Omit<Task, 'detectedLanguage'>[] = [
  {
    id: "T34567",
    title: "Fix JavaScript error in Gadget-Gallery",
    createdAt: "2023-11-11",
    tags: ["good first task", "easy", "JavaScript", "Gadgets"],
    subscribers: 2,
    description: "There is a TypeError when opening the image gallery gadget. Seems to be related to `mw.loader.using`. Needs a fix in gallery.js.",
    phabricatorUrl: "https://phabricator.wikimedia.org/T34567",
    gerritUrl: "https://gerrit.wikimedia.org/r/c/mediawiki/gadgets/Gallery/+/987654"
  },
  {
    id: "T45678",
    title: "Add structured logging to pywikibot task runner",
    createdAt: "2024-05-22",
    tags: ["bots", "Python", "pywikibot", "medium"],
    subscribers: 1,
    description: "The current bot framework uses simple print statements for logging. We need to implement structured logging using the standard logging library in Python for better parsing and analysis.",
    phabricatorUrl: "https://phabricator.wikimedia.org/T45678",
  },
  {
    id: "T56789",
    title: "Optimize Lua module for template parameter checking",
    createdAt: "2024-04-15",
    tags: ["Lua", "performance", "Scribunto", "hard"],
    subscribers: 5,
    description: "The TemplateWizard module is causing performance issues on pages with many templates. The parameter checking function needs to be optimized. This task involves deep knowledge of Lua and Scribunto performance tuning.",
    phabricatorUrl: "https://phabricator.wikimedia.org/T56789",
  },
  {
    id: "T12345",
    title: "Update documentation for login form accessibility",
    createdAt: "2024-06-01",
    tags: ["good first task", "easy", "documentation"],
    subscribers: 0,
    description: "The documentation for the main login form is missing ARIA attributes. We need to update the developer docs to include best practices. No code change needed, just updating a wiki page.",
    phabricatorUrl: "https://phabricator.wikimedia.org/T12345",
  },
  {
    id: "T23456",
    title: "[Bot] Create a new bot to archive stale discussions",
    createdAt: "2023-09-30",
    tags: ["bots", "Python", "community-wishlist"],
    subscribers: 8,
    description: "A new bot is requested by the community to automatically archive talk page sections that have not been active for 90 days. This requires using pywikibot and handling various edge cases.",
    phabricatorUrl: "https://phabricator.wikimedia.org/T23456",
    gerritUrl: "https://gerrit.wikimedia.org/r/c/pywikibot/core/+/123123"
  },
  {
    id: "T67890",
    title: "Refactor legacy PHP backend for the Echo service",
    createdAt: "2024-03-10",
    tags: ["PHP", "backend", "Echo", "hard", "refactoring"],
    subscribers: 12,
    description: "The notification system (Echo) has some legacy PHP code that needs to be modernized to use newer language features and improve performance. This is a large-scale refactoring task.",
    phabricatorUrl: "https://phabricator.wikimedia.org/T67890",
  },
  {
    id: "T78901",
    title: "Improve mobile UI for search results page",
    createdAt: "2024-06-10",
    tags: ["good first task", "easy", "JavaScript", "CSS", "mobile"],
    subscribers: 1,
    description: "On small screens, the search results are not wrapping correctly. This is likely a CSS issue, maybe related to flexbox. The fix should be in the main mobile.less file and might need a tiny bit of JS.",
    phabricatorUrl: "https://phabricator.wikimedia.org/T78901",
  },
  {
    id: "T89012",
    title: "Automated script to update Lua module dependencies",
    createdAt: "2024-01-20",
    tags: ["bots", "Lua", "automation", "medium"],
    subscribers: 3,
    description: "We need a script that can scan Lua modules for `require()` statements and build a dependency graph. This will help in automated testing and deployment. Can be written in Python or Lua.",
    phabricatorUrl: "https://phabricator.wikimedia.org/T89012",
  },
  {
    id: "T90123",
    title: "Fix broken links in PHP-based API documentation",
    createdAt: "2024-06-15",
    tags: ["good first task", "PHP", "documentation", "easy"],
    subscribers: 2,
    description: "Some links in the auto-generated API documentation for our PHP libraries are pointing to old URLs. This task involves finding the configuration file for the doc generator and updating the base URL.",
    phabricatorUrl: "https://phabricator.wikimedia.org/T90123",
  },
   {
    id: "T91124",
    title: "Add a 'copy to clipboard' button for code snippets",
    createdAt: "2024-06-18",
    tags: ["good first task", "JavaScript", "easy", "enhancement"],
    subscribers: 1,
    description: "Users want a small 'copy' button on all `<pre>` and `<code>` blocks in the documentation. This should be implemented as a lightweight, dependency-free JavaScript enhancement.",
    phabricatorUrl: "https://phabricator.wikimedia.org/T91124",
  }
];
